package cn.edu.nju.software.soa.archive;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-01-10T16:39:50.441+08:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://archive.soa.software.nju.edu.cn/", name = "ArchiveService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ArchiveService {

    @WebMethod
    @Action(input = "http://archive.soa.software.nju.edu.cn/ArchiveService/updateRequest", output = "http://archive.soa.software.nju.edu.cn/ArchiveService/updateResponse")
    @WebResult(name = "parameters", targetNamespace = "", partName = "parameters")
    public UpdateResponse update(

        @WebParam(partName = "updateRequest", name = "updateRequest", targetNamespace = "")
        UpdateRequest updateRequest
    );

    @WebMethod
    @Action(input = "http://archive.soa.software.nju.edu.cn/ArchiveService/addRequest", output = "http://archive.soa.software.nju.edu.cn/ArchiveService/addResponse")
    @WebResult(name = "parameters", targetNamespace = "", partName = "parameters")
    public AddResponse add(

        @WebParam(partName = "addRequest", name = "addRequest", targetNamespace = "")
        AddRequest addRequest
    );

    @WebMethod
    @Action(input = "http://archive.soa.software.nju.edu.cn/ArchiveService/queryRequest", output = "http://archive.soa.software.nju.edu.cn/ArchiveService/queryResponse")
    @WebResult(name = "parameters", targetNamespace = "", partName = "parameters")
    public QueryResponse query(

        @WebParam(partName = "queryRequest", name = "queryRequest", targetNamespace = "")
        QueryRequest queryRequest
    );

    @WebMethod
    @Action(input = "http://archive.soa.software.nju.edu.cn/ArchiveService/deleteRequest", output = "http://archive.soa.software.nju.edu.cn/ArchiveService/deleteResponse")
    @WebResult(name = "parameters", targetNamespace = "", partName = "parameters")
    public DeleteResponse delete(

        @WebParam(partName = "deleteRequest", name = "deleteRequest", targetNamespace = "")
        DeleteRequest deleteRequest
    );
}
