package cn.edu.nju.software.soa.archive;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-01-10T16:39:50.474+08:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "ArchiveService",
                  wsdlLocation = "file:/Users/zhengyi/Desktop/NJU/大四上/面向服务的软件工程/code/assignment-two/archive-service/src/main/resources/ArchiveService.wsdl",
                  targetNamespace = "http://archive.soa.software.nju.edu.cn/")
public class ArchiveService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://archive.soa.software.nju.edu.cn/", "ArchiveService");
    public final static QName ArchiveServicePort = new QName("http://archive.soa.software.nju.edu.cn/", "ArchiveServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/zhengyi/Desktop/NJU/大四上/面向服务的软件工程/code/assignment-two/archive-service/src/main/resources/ArchiveService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ArchiveService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/zhengyi/Desktop/NJU/大四上/面向服务的软件工程/code/assignment-two/archive-service/src/main/resources/ArchiveService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ArchiveService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ArchiveService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArchiveService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ArchiveService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ArchiveService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ArchiveService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ArchiveService
     */
    @WebEndpoint(name = "ArchiveServicePort")
    public ArchiveService getArchiveServicePort() {
        return super.getPort(ArchiveServicePort, ArchiveService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArchiveService
     */
    @WebEndpoint(name = "ArchiveServicePort")
    public ArchiveService getArchiveServicePort(WebServiceFeature... features) {
        return super.getPort(ArchiveServicePort, ArchiveService.class, features);
    }

}
