
package cn.edu.nju.software.soa.archive;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArchiveService", targetNamespace = "http://archive.soa.software.nju.edu.cn/", wsdlLocation = "http://localhost:8082/archive?wsdl")
public class ArchiveService_Service
    extends Service
{

    private final static URL ARCHIVESERVICE_WSDL_LOCATION;
    private final static WebServiceException ARCHIVESERVICE_EXCEPTION;
    private final static QName ARCHIVESERVICE_QNAME = new QName("http://archive.soa.software.nju.edu.cn/", "ArchiveService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/archive?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARCHIVESERVICE_WSDL_LOCATION = url;
        ARCHIVESERVICE_EXCEPTION = e;
    }

    public ArchiveService_Service() {
        super(__getWsdlLocation(), ARCHIVESERVICE_QNAME);
    }

    public ArchiveService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARCHIVESERVICE_QNAME, features);
    }

    public ArchiveService_Service(URL wsdlLocation) {
        super(wsdlLocation, ARCHIVESERVICE_QNAME);
    }

    public ArchiveService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARCHIVESERVICE_QNAME, features);
    }

    public ArchiveService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArchiveService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ArchiveService
     */
    @WebEndpoint(name = "ArchiveServicePort")
    public ArchiveService getArchiveServicePort() {
        return super.getPort(new QName("http://archive.soa.software.nju.edu.cn/", "ArchiveServicePort"), ArchiveService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArchiveService
     */
    @WebEndpoint(name = "ArchiveServicePort")
    public ArchiveService getArchiveServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://archive.soa.software.nju.edu.cn/", "ArchiveServicePort"), ArchiveService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARCHIVESERVICE_EXCEPTION!= null) {
            throw ARCHIVESERVICE_EXCEPTION;
        }
        return ARCHIVESERVICE_WSDL_LOCATION;
    }

}
