
package cn.edu.nju.software.soa.archive;

import java.math.BigInteger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import cn.edu.nju.software.soa.archive.schema.LoginInfo;
import cn.edu.nju.software.soa.archive.schema.StudentInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ArchiveService", targetNamespace = "http://archive.soa.software.nju.edu.cn/")
@XmlSeeAlso({
    cn.edu.nju.software.soa.archive.ObjectFactory.class,
    cn.edu.nju.software.soa.archive.schema.ObjectFactory.class
})
public interface ArchiveService {


    /**
     * 
     * @param password
     * @param code
     * @param gender
     * @param data
     * @param loginInfo
     * @param name
     * @param id
     * @param message
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://archive.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.archive.schema.AddRequest")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://archive.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.archive.schema.AddResponse")
    @Action(input = "http://archive.soa.software.nju.edu.cn/ArchiveService/addRequest", output = "http://archive.soa.software.nju.edu.cn/ArchiveService/addResponse")
    public void add(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "gender", targetNamespace = "")
        String gender,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<BigInteger> code,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Boolean> data);

    /**
     * 
     * @param password
     * @param code
     * @param gender
     * @param data
     * @param loginInfo
     * @param name
     * @param id
     * @param message
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://archive.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.archive.schema.UpdateRequest")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://archive.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.archive.schema.UpdateResponse")
    @Action(input = "http://archive.soa.software.nju.edu.cn/ArchiveService/updateRequest", output = "http://archive.soa.software.nju.edu.cn/ArchiveService/updateResponse")
    public void update(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "gender", targetNamespace = "")
        String gender,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<BigInteger> code,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StudentInfo> data);

    /**
     * 
     * @param code
     * @param data
     * @param loginInfo
     * @param id
     * @param message
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://archive.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.archive.schema.DeleteRequest")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://archive.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.archive.schema.DeleteResponse")
    @Action(input = "http://archive.soa.software.nju.edu.cn/ArchiveService/deleteRequest", output = "http://archive.soa.software.nju.edu.cn/ArchiveService/deleteResponse")
    public void delete(
        @WebParam(name = "loginInfo", targetNamespace = "")
        LoginInfo loginInfo,
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<BigInteger> code,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Boolean> data);

    /**
     * 
     * @param password
     * @param code
     * @param data
     * @param message
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "query", targetNamespace = "http://archive.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.archive.schema.QueryRequest")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://archive.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.archive.schema.QueryResponse")
    @Action(input = "http://archive.soa.software.nju.edu.cn/ArchiveService/queryRequest", output = "http://archive.soa.software.nju.edu.cn/ArchiveService/queryResponse")
    public void query(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<BigInteger> code,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<StudentInfo> data);

}
