
package cn.edu.nju.software.soa.signin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SigninService", targetNamespace = "http://signin.soa.software.nju.edu.cn/", wsdlLocation = "http://localhost:8081/signin?wsdl")
public class SigninService_Service
    extends Service
{

    private final static URL SIGNINSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIGNINSERVICE_EXCEPTION;
    private final static QName SIGNINSERVICE_QNAME = new QName("http://signin.soa.software.nju.edu.cn/", "SigninService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/signin?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIGNINSERVICE_WSDL_LOCATION = url;
        SIGNINSERVICE_EXCEPTION = e;
    }

    public SigninService_Service() {
        super(__getWsdlLocation(), SIGNINSERVICE_QNAME);
    }

    public SigninService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIGNINSERVICE_QNAME, features);
    }

    public SigninService_Service(URL wsdlLocation) {
        super(wsdlLocation, SIGNINSERVICE_QNAME);
    }

    public SigninService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIGNINSERVICE_QNAME, features);
    }

    public SigninService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SigninService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SigninService
     */
    @WebEndpoint(name = "SigninServicePort")
    public SigninService getSigninServicePort() {
        return super.getPort(new QName("http://signin.soa.software.nju.edu.cn/", "SigninServicePort"), SigninService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SigninService
     */
    @WebEndpoint(name = "SigninServicePort")
    public SigninService getSigninServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://signin.soa.software.nju.edu.cn/", "SigninServicePort"), SigninService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIGNINSERVICE_EXCEPTION!= null) {
            throw SIGNINSERVICE_EXCEPTION;
        }
        return SIGNINSERVICE_WSDL_LOCATION;
    }

}
