
package cn.edu.nju.software.soa.signin;

import java.math.BigInteger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SigninService", targetNamespace = "http://signin.soa.software.nju.edu.cn/")
@XmlSeeAlso({
    cn.edu.nju.software.soa.signin.ObjectFactory.class,
    cn.edu.nju.software.soa.signin.schema.ObjectFactory.class
})
public interface SigninService {


    /**
     * 
     * @param password
     * @param code
     * @param message
     * @param email
     * @param signinCode
     * @param status
     */
    @WebMethod
    @RequestWrapper(localName = "signin", targetNamespace = "http://signin.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.signin.schema.SigninRequest")
    @ResponseWrapper(localName = "signinResponse", targetNamespace = "http://signin.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.signin.schema.SigninResponse")
    @Action(input = "http://signin.soa.software.nju.edu.cn/SigninService/signinRequest", output = "http://signin.soa.software.nju.edu.cn/SigninService/signinResponse")
    public void signin(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "signinCode", targetNamespace = "")
        String signinCode,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<BigInteger> code,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> status);

}
