package cn.edu.nju.software.soa.signin;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-01-10T17:00:18.092+08:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://signin.soa.software.nju.edu.cn/", name = "SigninService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SigninService {

    @WebMethod
    @Action(input = "http://signin.soa.software.nju.edu.cn/SigninService/signinRequest", output = "http://signin.soa.software.nju.edu.cn/SigninService/signinResponse")
    @WebResult(name = "parameters", targetNamespace = "", partName = "parameters")
    public SigninResponse signin(

        @WebParam(partName = "parameters", name = "parameters", targetNamespace = "")
        SigninRequest parameters
    );
}
