package cn.edu.nju.software.soa.signin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-01-10T17:00:18.115+08:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "SigninService",
                  wsdlLocation = "file:/Users/zhengyi/Desktop/NJU/大四上/面向服务的软件工程/code/assignment-two/signin-service/src/main/resources/SigninService.wsdl",
                  targetNamespace = "http://signin.soa.software.nju.edu.cn/")
public class SigninService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://signin.soa.software.nju.edu.cn/", "SigninService");
    public final static QName SigninServicePort = new QName("http://signin.soa.software.nju.edu.cn/", "SigninServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/zhengyi/Desktop/NJU/大四上/面向服务的软件工程/code/assignment-two/signin-service/src/main/resources/SigninService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SigninService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/zhengyi/Desktop/NJU/大四上/面向服务的软件工程/code/assignment-two/signin-service/src/main/resources/SigninService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SigninService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SigninService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SigninService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SigninService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SigninService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SigninService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SigninService
     */
    @WebEndpoint(name = "SigninServicePort")
    public SigninService getSigninServicePort() {
        return super.getPort(SigninServicePort, SigninService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SigninService
     */
    @WebEndpoint(name = "SigninServicePort")
    public SigninService getSigninServicePort(WebServiceFeature... features) {
        return super.getPort(SigninServicePort, SigninService.class, features);
    }

}
