
package cn.edu.nju.software.soa.login;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import cn.edu.nju.software.soa.login.schema.LoginRequest;
import cn.edu.nju.software.soa.login.schema.LoginResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginService", targetNamespace = "http://login.soa.software.nju.edu.cn/")
@XmlSeeAlso({
    cn.edu.nju.software.soa.login.ObjectFactory.class,
    cn.edu.nju.software.soa.login.schema.ObjectFactory.class
})
public interface LoginService {


    /**
     * 
     * @param arg0
     * @return
     *     returns cn.edu.nju.software.soa.login.schema.LoginResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://login.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.login.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://login.soa.software.nju.edu.cn/", className = "cn.edu.nju.software.soa.login.LoginResponse")
    @Action(input = "http://login.soa.software.nju.edu.cn/LoginService/loginRequest", output = "http://login.soa.software.nju.edu.cn/LoginService/loginResponse")
    public LoginResponse login(
        @WebParam(name = "arg0", targetNamespace = "")
        LoginRequest arg0);

}
